version: "3.5"

networks:
  edge:
    name: "edge"

services:

  "${CUSTOMER_NAME}-mysql":
    image: "mysql:5.7"
    container_name: "wp-mysql"
    networks:
      - "edge"
    volumes:
      - "./wp-mysql/var/lib/mysql:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "wordpress"
      MYSQL_USER: "wordpress"
      MYSQL_PASSWORD: "${DB_USER_PASSWORD}"

  "${CUSTOMER_NAME}-wordpress":
    depends_on:
      - "wp-mysql"
    image: "wordpress:latest"
    container_name: "wp-wordpress"
    networks:
      - "wp"
    volumes:
      - "./wp-wordpress/var/www/html:/var/www/html"
    environment:
      WORDPRESS_DB_HOST: "wp-mysql:3306"
      WORDPRESS_DB_USER: "wordpress"
      WORDPRESS_DB_PASSWORD: "${DB_USER_PASSWORD}"
